- name: RoboShop Frontend setup
  hosts: FRONTEND
  become: yes
  tags: frontend
  roles:
    - name: frontend

- name: RoboShop MongoDB setup
  hosts: MONGODB
  become: yes
  tags: mongodb
  roles:
    - name: mongodb

- name: RoboShop Catalogue setup
  hosts: CATALOGUE
  become: yes
  tags: catalogue
  roles:
    - name: catalogue

- name: RoboShop Redis setup
  hosts: REDIS
  become: yes
  tags: redis
  roles:
    - name: redis

- name: RoboShop User setup
  hosts: USER
  become: yes
  tags: user
  roles:
    - name: user

- name: RoboShop Cart setup
  hosts: CART
  become: yes
  tags: cart
  roles:
    - name: cart

- name: RoboShop MySQL setup
  hosts: MYSQL
  become: yes
  tags: mysql
  roles:
    - name: mysql

- name: RoboShop Shipping setup
  hosts: SHIPPING
  become: yes
  tags: shipping
  roles:
    - name: shipping

- name: RoboShop RabbitMQ
  hosts: RABBITMQ
  become: yes
  tags: rabbitmq
  roles:
    - name: rabbitmq