- name: Add Application USER
  ansible.builtin.user:
    name: roboshop
    state: present

- name: Download
  ansible.builtin.include_tasks:
    file: download-from-github.yml

- name: Delete old Content
  ansible.builtin.file:
    path: /home/roboshop/{{ COMPONENT }}
    state: absent
  ignore_errors: yes

- name: Copy {{ COMPONENT }} Content
  ansible.builtin.copy:
    src: /tmp/{{ COMPONENT }}-main/
    dest: /home/roboshop/{{ COMPONENT }}/
    remote_src: yes
    owner: roboshop
    group: roboshop